title: Lewis Gaul's website
url: "https://lewisgaul.github.io"
baseurl: ""

# Navigation
nav:
  - name: Home
    href: /
  - name: EnHackathon blog
    href: https://enhackathon.github.io
  - name: Artwork site
    href: https://lewisgaul.github.io/artwork-site
#  - name: Language Comparison
#    href: https://lewisgaul.github.io/LanguageComparison

include: ['_pages']


markdown: kramdown
