title: Lewis Gaul
baseurl: ""
comments_locked: true

markdown: kramdown
kramdown:
  input: GFM  # Github-Flavoured Markdown
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-toc

# Navigation
nav:
  - name: Home
    href: /
  - name: Blog
    href: /blog
#  - name: CV
#    href: /cv
  - name: EnHackathon
    href: https://enhackathon.github.io

collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
    values:
      toc: true
