title: Lewis Gaul's Homepage
#url: "https://lewisgaul.github.io"
baseurl: ""

# Navigation
nav:
  - name: Home
    href: /
  - name: CV
    href: /cv.html
  - name: Minegauler
    href: /minegauler.html
  - name: EnHackathon
    href: https://enhackathon.github.io
  - name: Artwork site
    href: https://lewisgaul.github.io/artwork-site
#  - name: Language Comparison
#    href: https://lewisgaul.github.io/LanguageComparison

markdown: kramdown
