title: Lewis Gaul - Homepage
baseurl: ""
comments_locked: false

markdown: kramdown
kramdown:
  input: GFM  # Github-Flavoured Markdown
  syntax_highlighter: rouge

plugins: [jekyll-seo-tag]

# Navigation
nav:
  - name: Home
    href: /
  - name: CV
    href: /cv
  - name: Minegauler
    href: /minegauler
  - name: Blog
    href: /blog
  - name: EnHackathon
    href: https://enhackathon.github.io
  - name: Artwork site
    href: https://lewisgaul.github.io/artwork-site

collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/
